In [1]:
import pandas as pd
import numpy as np
import gzip, pickle

In [72]:
with gzip.open("/data/remote/pytorch_emotion/Feature/feature.pkl") as ifp:
    df = pickle.load(ifp)

In [4]:
em = pd.read_csv("/data/remote/pytorch_emotion/Feature/emotion_classes.csv")

In [ ]:
%%time
for i in range(df.shape[0]):
    df["session"] = df.name[i][0:5]
    df["type"] = df.name[i][7:12]
    if i % 10000 == 0:
        print("{} / {}".format(i, df.shape[0]))

0 / 4467131


In [93]:
df.tail()

name  frameTime  pcm_RMSenergy_sma  \
4467126  Ses05M_script01_3_M018       1.87           0.000198   
4467127  Ses05M_script01_3_M018       1.88           0.000195   
4467128  Ses05M_script01_3_M018       1.89           0.000193   
4467129  Ses05M_script01_3_M018       1.90           0.000198   
4467130  Ses05M_script01_3_M018       1.90           0.000199   

         pcm_fftMag_mfcc_sma[1]  pcm_fftMag_mfcc_sma[2]  \
4467126               -3.459800               -5.763472   
4467127               -3.376133               -5.337474   
4467128               -3.508446               -5.726255   
4467129               -3.805887               -5.993629   
4467130               -4.270571               -7.124331   

         pcm_fftMag_mfcc_sma[3]  pcm_fftMag_mfcc_sma[4]  \
4467126                0.841579               -9.695216   
4467127                1.874752               -9.042918   
4467128                2.737298               -8.980531   
4467129                4.214068               -7.692686   
4467130                4.209899               -7.191917   

         pcm_fftMag_mfcc_sma[5]  pcm_fftMag_mfcc_sma[6]  \
4467126                4.484260               -9.267400   
4467127                6.292750               -6.939490   
4467128                6.181498               -6.482841   
4467129                6.985946               -4.494845   
4467130                6.929283               -3.908572   

         pcm_fftMag_mfcc_sma[7]  ...  pcm_fftMag_mfcc_sma_de[9]  \
4467126                4.476427  ...                  -0.251568   
4467127                9.076157  ...                   0.012340   
4467128                7.800995  ...                   0.271353   
4467129                8.533830  ...                   0.288189   
4467130                7.171572  ...                   0.131741   

         pcm_fftMag_mfcc_sma_de[10]  pcm_fftMag_mfcc_sma_de[11]  \
4467126                   -0.365525                    1.263438   
4467127                    0.221922                    1.592537   
4467128                    0.992430                    1.109989   
4467129                    1.509172                    0.529629   
4467130                    1.078309                    0.125612   

         pcm_fftMag_mfcc_sma_de[12]  pcm_zcr_sma_de  voiceProb_sma_de  \
4467126                    1.445976       -0.010667         -0.006270   
4467127                    1.574733       -0.008333         -0.005351   
4467128                    0.909039       -0.004083         -0.011039   
4467129                    0.115002       -0.001000         -0.009969   
4467130                   -0.279673        0.000500         -0.006122   

         F0_sma_de  class   type  session  
4467126        0.0      ?  scrip    Ses01  
4467127        0.0      ?  scrip    Ses01  
4467128        0.0      ?  scrip    Ses01  
4467129        0.0      ?  scrip    Ses01  
4467130        0.0      ?  scrip    Ses01  

[5 rows x 37 columns]

In [5]:
em

Unnamed: 0               TURN_NAME EMOTION
0               0     Ses01F_impro01_F000     neu
1               1     Ses01F_impro01_F001     neu
2               2     Ses01F_impro01_F002     neu
3               3     Ses01F_impro01_F003     xxx
4               4     Ses01F_impro01_F004     xxx
...           ...                     ...     ...
10033       10033  Ses05M_script03_2_M041     ang
10034       10034  Ses05M_script03_2_M042     ang
10035       10035  Ses05M_script03_2_M043     ang
10036       10036  Ses05M_script03_2_M044     ang
10037       10037  Ses05M_script03_2_M045     ang

[10038 rows x 3 columns]

In [5]:
need = list(data.columns)[2:-1]

In [7]:
em.EMOTION[0]

'neu'

In [8]:
data[data.name == em.TURN_NAME[0]][need].to_numpy().shape

(194, 32)

In [9]:
leng = em.shape[0]
emo = ['neu', 'ang', 'sad', 'hap', 'exc']
x = []
y = []
ses = []
tp = []
for i in range(leng):
    tmp = data[data.name == em.TURN_NAME[i]][need]
    arr = tmp.to_numpy()
    tmp_emo = em.EMOTION[i]
    if tmp_emo in emo:
        x.append(arr)
        y.append(tmp_emo)
        
    if i % 1000 == 0:
        print("{} / {}".format(i, leng))
data = np.array(x)
label = np.array(y)
    

0 / 10038
1000 / 10038
2000 / 10038
3000 / 10038
4000 / 10038
5000 / 10038
6000 / 10038
7000 / 10038
8000 / 10038
9000 / 10038
10000 / 10038


In [10]:
data.shape

(10038,)

In [21]:
data[0].shape

(194, 32)

In [22]:
data[1].shape

(137, 32)

In [16]:
label[1]

'neu'

In [26]:
t = np.dstack((data[0], data[1]))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 194 and the array at index 1 has size 137

In [19]:
t.shape

(331, 32)

In [25]:
np.append(data[0], data[1]).shape

(10592,)

In [28]:
for i in range(data.shape[0]):
    data[i].reshape((1, data[i].shape[0], 32))

In [29]:
data.shape

(10038,)

In [31]:
data[0].shape

(194, 32)

In [32]:
def pprint(arr):
    print("type:{}".format(type(arr)))
    print("shape: {}, dimension: {}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)

In [ ]:
pprint(data)

In [34]:
data.size

10038

In [35]:
type(data[0])

numpy.ndarray

In [36]:
type(data)

numpy.ndarray

In [37]:
y = np.ones((1,1,1))

In [38]:
y

array([[[1.]]])

In [40]:
np.concatenate((y,data[0]))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [42]:
t = data[0].reshape(1, data[0].shape[0], 32)

In [43]:
t.shape

(1, 194, 32)

In [45]:
s = data[1].reshape(1, data[1].shape[0], 32)

In [48]:
ma = []
for i in range(data.shape[0]):
    ma.append(data[i].shape[0])
max(ma)

3413

In [57]:
a = [[1,2],[3,4]]
b = [[3,4], [4,5]]

In [58]:
a = np.array(a)
b = np.array(b)

In [59]:
a.shape

(2, 2)

In [60]:
a

array([[1, 2],
       [3, 4]])

In [70]:
exc = np.where(label == 'exc')[0]
hap = np.where(label == 'hap')[0]
ang = np.where(label == 'ang')[0]
neu = np.where(label == 'neu')[0]
sad = np.where(label == 'sad')[0]

In [75]:
name = df.name.to_numpy()

In [76]:
name

array(['Ses01M_script03_1_M031', 'Ses01M_script03_1_M031',
       'Ses01M_script03_1_M031', ..., 'Ses05M_script01_3_M018',
       'Ses05M_script01_3_M018', 'Ses05M_script01_3_M018'], dtype=object)

In [81]:
np.where(name[0:5] == "Ses01M_script03_1_M031")

(array([0, 1, 2, 3, 4]),)

In [79]:
name[0][0:5]

'Ses01'